[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Environment variables for production
[context.production.environment]
  VITE_RELAYER_URL = "https://discerning-wonder-production-3da7.up.railway.app"
  VITE_CONTRACT_ADDRESS = "0x48D3250BC9d205877E3D496B20d824dc2Cd4FA96"
  VITE_BLOCKCHAIN_RPC_URL = "https://data-seed-prebsc-1-s1.binance.org:8545/"
  VITE_FIREBASE_API_KEY = "your-firebase-api-key"
  VITE_FIREBASE_AUTH_DOMAIN = "your-firebase-auth-domain"
  VITE_FIREBASE_PROJECT_ID = "your-firebase-project-id"